# Generated by Django 4.0 on 2021-12-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exp',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='exp',
            name='summary',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
