# Generated by Django 4.0 on 2021-12-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0002_exp_title_alter_exp_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exp',
            name='summary',
            field=models.TextField(),
        ),
    ]
